// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

let lovableAuth: any = null;

try {
  const mod = await import("@lovable.dev/cloud-auth-js");
  lovableAuth = mod.createLovableAuth();
} catch {
  // Cloud auth not available — social login will be disabled
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      if (!lovableAuth) {
        return { error: new Error("Login social não disponível. Configure o Lovable Cloud.") };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) return result;
      if (result.error) return result;

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};