// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

let lovableAuth: any = null;
let authInitPromise: Promise<void> | null = null;

function initAuth() {
  if (!authInitPromise) {
    authInitPromise = import("@lovable.dev/cloud-auth-js")
      .then((mod) => {
        lovableAuth = mod.createLovableAuth();
      })
      .catch(() => {
        // Cloud auth not available
      });
  }
  return authInitPromise;
}

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      await initAuth();
      
      if (!lovableAuth) {
        return { error: new Error("Login social não disponível. Configure o Lovable Cloud.") };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: { ...opts?.extraParams },
      });

      if (result.redirected || result.error) return result;

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};