// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './db-types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://mkbxkemuqlfakvfuqgpq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYnhrZW11cWxmYWt2ZnVxZ3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNjc0NzYsImV4cCI6MjA4ODc0MzQ3Nn0.lntocTOUYmnY3GxAsMaY9ep0K6B9jewsuZjqIdI6IWM';

export const supabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

let _supabase: SupabaseClient<Database> | null = null;

function getSupabaseClient(): SupabaseClient<Database> {
  if (!_supabase) {
    if (!supabaseConfigured) {
      // Create a dummy client that won't crash but won't work either
      _supabase = createClient<Database>(
        'https://placeholder.supabase.co',
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2MDAwMDAwMDAsImV4cCI6MTkwMDAwMDAwMH0.placeholder'
      );
    } else {
      _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      });
    }
  }
  return _supabase;
}

export const supabase = getSupabaseClient();